name: Submit dependencies
description: Generates a GitHub-ready dependency report for the given module and submits it
inputs:
  module:
    description: The target module
    required: true
  github-token:
    description: The value of GITHUB_TOKEN
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - run: .scripts/dependency_report_generate.sh -m ${{ inputs.module }} -c allSourceSetsCompileDependenciesMetadata > dependencies_${{ inputs.module }}_raw
      shell: bash
    - run: .scripts/github/dependency_report_as_github_json.sh -i dependencies_${{ inputs.module }}_raw -n ${{ inputs.module }} -s $(TZ=UTC date +"%Y-%m-%dT%H:%M:%SZ") -l ${{ inputs.module }}/build.gradle.kts > dependencies_${{ inputs.module }}.github.json
      shell: bash
    - run: |
        echo RESPONSE_CODE=$(curl -L \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer ${{ inputs.github-token }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/$GITHUB_REPOSITORY/dependency-graph/snapshots \
         --data-binary "@dependencies_${{ inputs.module }}.github.json" \
         -o /dev/null \
         -w '%{http_code}') >> $GITHUB_ENV
      shell: bash
    - run: |
        if [[ "$RESPONSE_CODE" == "201" ]];
         then
           exit 0
         else
           echo "Dependency submission failed with HTTP code $RESPONSE_CODE"
           exit 1
         fi
      shell: bash
