name: Publish
on: workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_IN_MEMORY_KEY }}
concurrency:
  group: ${{ github.ref_name }}
jobs:
  create-github-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.ref_name }}
      - run: .scripts/github/release.sh
  publish-maven-publications:
    runs-on: macos-14-xlarge
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/runGradleTask
        with:
          preTaskString: -Pversion=$GITHUB_REF_NAME
          task: publishToMavenCentral --continue --no-configuration-cache
