name: Static analysis
on:
  push:
    branches:
      - '**'
jobs:
  ktlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
      - run: .scripts/check_ktlint.sh
  codeql:
    runs-on: macos-14-xlarge
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: github/codeql-action/init@v3.25.6
        with:
          languages: kotlin
      - uses: ./.github/actions/runGradleTask
        with:
          task: build
      - uses: github/codeql-action/analyze@v3.25.6
        with:
          category: "/language:kotlin"

